name: gis_task
description: A Task made for Go India Stocks

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Functional Programming
  dartz: ^0.10.1
  # Better Value Equality
  equatable: ^2.0.3
  # Network checker
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
